Repository opherlabs/gaming-components, pull requests merged in 2024-09, with the labels that each got.

#45 [Unity in Diversity] Create landing page
  components/next.config.mjs
  components/public/IconHeartWhite.svg
  components/public/IconSACountryWhite.svg
  components/public/IconSAFlagRoundWhite.svg
  components/public/IconSunWhite.svg
  components/public/SA Flag 1920x1080.svg
  components/public/Saflag.webp
  components/public/flasSa.svg
  components/public/sa.svg
  components/src/app/home/page.tsx
  components/src/app/page.tsx
  components/src/components/LandingPage/ImageGallery.tsx
  components/src/components/LandingPage/LandingPageData.ts
  components/src/components/LandingPage/MainLandingPage.tsx
  components/src/components/LandingPage/SmallRoundedImageGallery .tsx
  components/src/components/LandingPage/index.ts
  components/src/components/LandingPage/landingPageDto.ts
  components/src/components/index.ts
  components/tsconfig.json
Labels: enhancement, Review effort [1-5]: 3

#46 Quiz cards
  components/public/cards/Fwd_ latest version of the Art.zip
  components/public/cards/Fwd_ latest version of the Art/Icon SA Flag Round White 256x256.svg
  components/public/cards/Fwd_ latest version of the Art/Icon Sun White 256x256.svg
  components/public/cards/Fwd_ latest version of the Art/SA Flag 1920x1080.svg
  components/public/cards/Fwd_ latest version of the Art/heartwhite.svg
  components/public/cards/Fwd_ latest version of the Art/sacountrywhite.svg
  components/public/cards/blue.jpeg
  components/public/cards/countrywhite.svg
  components/public/cards/flag.svg
  components/public/cards/flaground
  components/public/cards/green.jpeg
  components/public/cards/heart.svg
  components/public/cards/light.webp
  components/public/cards/pink.jpeg
  components/public/cards/sunwhite.svg
  components/src/app/cards/[id]/page.tsx
  components/src/app/cards/page.tsx
  components/src/app/page.tsx
  components/src/components/QuizCards/QuizCards.tsx
  components/src/components/QuizCards/QuizComponent.tsx
  components/src/components/QuizCards/StaticData.ts
  components/src/components/QuizCards/index.ts
  components/src/components/index.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, dependencies

#47 Created the company values questions card
  components/src/app/page.tsx
  components/src/components/CompanyValuesComponent.tsx
  components/src/components/ScoreButton.tsx
  components/src/components/index.ts
  pnpm-lock.yaml
Labels: enhancement, Other, Review effort [1-5]: 2

#48 Timer
  components/src/app/cards/[id]/page.tsx
  components/src/app/cards/page.tsx
  components/src/app/page.tsx
  components/src/components/QuizCards/QuizCards.tsx
  components/src/components/QuizCards/QuizComponent.tsx
  components/src/components/QuizCards/ScoreModal.tsx
  components/src/components/QuizCards/StaticData.ts
  components/src/components/QuizCards/index.ts
Labels: enhancement, Review effort [1-5]: 3, tests

#92 Framer motions on cards
  components/src/components/QuizCards/QuizCards.tsx
  components/src/components/QuizCards/QuizComponent.tsx
  components/src/components/QuizCards/StaticData.ts
Labels: enhancement, Review effort [1-5]: 3
